### ISSUE TITLE
Autorefresh when High Server load page occur

### ISSUE THREAD

**Issue by koohz** [DeathMiner/CsgoPrizes-Ticket-Farm#2]
![Issue](https://i.gyazo.com/bc54d6023c982d495ddf2c3b9e817992.png)

**Comment by demaisj** [comment]
Hello,
I noticed this bug a while ago: The farm is not refreshing when the servers have a high traffic rate. I'll do an update so we won't have to refresh manually in this case.

**Comment by demaisj** [comment]
I'm rolling out version 1.2, it should work now. If it is not working please reopen the issue (I can't test it there is no high load now)
