### ISSUE TITLE
Bad Bug

### ISSUE THREAD

**Issue by BenDover123** [DeathMiner/CsgoPrizes-Ticket-Farm#3]
I would say this script works for about an hour and then I get the cliched "Our servers are encountering high traffic right now" error. Normally I would say this is just their servers being under heavy load but when I go back to using the normally less efficient auto refresh tool, it works flawlessly and I can leave it on for several days with no issues. I'm not sure if they have some kind of way to detect these scripts but I am assuming the servers detect this script and then lock me out. It was the same with another script I was using too because of this issue. I can go back to csgoprizes after about 20 minutes of errors, but if I use the script the same thing will happen. Please tell me if its just me and if there is any way around it, thanks for the awesome script ^_^
P.S. When it goes to the high traffic page it tries to refresh, but I just end up in the same situation, same thing goes if I refresh myself.

**Comment by demaisj** [comment]
Hello,

Thanks for reporting this issue. Usually I run this farm on the background so I didn't noticed that. I'm going to do some research about it.

**Comment by BenDover123** [comment]
It seems to be working fine for me now, I don't know why. I'm assuming it was their servers but either way, thanks for taking the time to check into my problem and making this awesome script!

**Comment by demaisj** [comment]
I'll close this issue for now. Feel free to reopen it if the problem comes back.
By the way thanks for using this script, if you have any suggestions tell me!
