### ISSUE TITLE
Farm not working anymore 

### ISSUE THREAD

**Issue by furbas** [DeathMiner/CsgoPrizes-Ticket-Farm#4]
is there going to be an update to make it work again or no?

**Comment by demaisj** [comment]
Hi,

I noticed that the rewards.gg did a update breaking the script. Unfortunately, I'm kind of busy right now so I'll do the update maybe next week-end.
Anyway thanks for your support!

**Comment by demaisj** [comment]
Sorry, I didn't see that you posted this issue in the wrong repository: CsgoPrizes-LeaguePrizes-Ticket-Farm is no longer maintained, instead please download https://github.com/DeathMiner/RewardsGG-Farm (not working today)

**Comment by demaisj** [comment]
Hello, if you are looking for updates here is one fully working on the latest version of RewardsGG => https://github.com/DeathMiner/RewardsGG-Farm
